[tool.poetry]
name = "bentoctl"
version = "0.1.1"
description = "Fast model deployment with BentoML on cloud platforms."
authors = ["bentoml.org <contact@bentoml.ai>"]
homepage = "https://github.com/bentoml/bentoctl"
readme = "./README.md"
license = "Apache-2.0"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development",
]

[tool.poetry.scripts]
bentoctl = "bentoctl.cli:bentoctl"

[tool.poetry.urls]
"Source" =  "https://github.com/bentoml/bentoctl"
"User Slack community" = "https://bit.ly/2N5IpbB"
"Bug Reports" = "https://github.com/bentoml/bentoctl/issues"

[tool.poetry.dependencies]
python = "^3.7"
bentoml = {version="^1.0.0*", allow-prereleases=true}
click = "^8"
cerberus = "^1"
rich = "^10"
cloup = "^0.12"
PyYaml = "^6"
simple-term-menu = "0.4.4"
GitPython = "3.1.24"
importlib-metadata = { version = "~=1.0", python = "<3.8" }

[tool.poetry.dev-dependencies]
flake8 = "^3.8.2"
pylint = "^2.6.2"
black = "*"
isort = "^5"
pytest = "^6"
pytest-cov = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
