contact_links:
  - name: bentoctl Discussions
    url: https://github.com/bentoml/bentoctl/discussions
    about: Please ask general questions here.
  - name: bentoctl Slack Community
    url: https://join.slack.bentoctl.org
    about: For connecting with others in the community
  - name: bentoctl Enterprise Support
    url: contact@bentoctl.ai
    about: Contact the bentoctl team and learn more
