name: BCDT-CI

on:
  push:
    branches: [ protype ]
  pull_request:
    branches: [ prototype ]
#  schedule:
#    - cron '0 2 * * *'

jobs:

  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run linting script
        run: ./ci/linter.sh
