name: Bentoctl-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron '0 2 * * *'

jobs:

  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run linting script
        run: ./ci/linter.sh

  unit_tests:
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches

      - name: Setup python
        uses: actions/setup-python@v2
        with :
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd

      - name: Run unit-tests
        run: ./ci/unit_tests.sh
        shell: bash

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-${{ matrix.os }}-python${{ matrix.python-version }}
          fail_ci_if_error: true
          flags: unit-tests
          directory: ./
          files: ./unit.xml
          verbose: true
