name: Bentoctl-CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
#  schedule:
#    - cron '0 2 * * *'

env:
  BENTOCTL_DO_NOT_TRACK: True
  BENTOML_DO_NOT_TRACK: True

jobs:

  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          cache: 'true'

      - name: Install test dependencies
        run: pdm install
      - name: Run linting script
        run: pdm lint

  unit_tests:
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.8', '3.11' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches

      - name: Setup python
        uses: pdm-project/setup-pdm@v3
        with :
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'true'

      - name: Install test dependencies
        run: pdm install

      - name: Run unit-tests
        run: pdm test
        shell: bash

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-${{ matrix.os }}-python${{ matrix.python-version }}
          fail_ci_if_error: true
          flags: unit-tests
          directory: ./
          files: ./unit.xml
          verbose: true
